export const USER_LOGIN = 'userLogin';
export const GROUPID = 'GP03';
export const LAYDANHSACHPHIM = 'LAY_DANH_SACH_PHIM'
export const LAYDANHSACHRAP = 'LAY_DANH_SACH_RAP';
export const SETCHITIETPHIM = 'SET_CHI_TIET_PHIM';
export const DANGNHAP = 'DANG_NHAP';
export const ACCESSTOKEN = 'accessToken';
export const GET_CHI_TIET_PHONG_VE = 'CHI_TIET_PHONG_VE';
export const DAT_GHE = 'DAT_GHE';
export const DOMAIN = 'http://movieapi.cyberlearn.vn';
export const tokenSyberSoft = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5Mb3AiOiJGcm9udCBFbmQgNjYiLCJIZXRIYW5TdHJpbmciOiIzMC8wMS8yMDIyIiwiSGV0SGFuVGltZSI6IjE2NDM1MDA4MDAwMDAiLCJuYmYiOjE2MTc1NTU2MDAsImV4cCI6MTY0MzY0ODQwMH0.ufODEd--n4Nm91XfL2RnIB9E1_kvZ4Dy1dyDst3wKuE'
// export const https = 'https://movienew.cybersoft.edu.vn' http://movieapi.cyberlearn.vn
export const http = 'http://movieapi.cyberlearn.vn'

export const SET_THONG_TIN_NGUOI_DUNG = 'SET_THONG_TIN_NGUOI_DUNG';
export const DISPLAY_LOADING = 'DISPLAY_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const DAT_VE_HOAN_TAT = 'DAT_VE_HOAN_TAT';
export const CHUYEN_TAB = 'CHUYEN_TAB';
export const CHANGE_TAB_ACTIVE = 'CHANGE_TAB_ACTIVE';
export const LOADING_API = 'LOADING_API';
export const HIDE_API = 'HIDE_API';
export const SET_THONG_TIN_PHIM = 'SET_THONG_TIN_PHIM'
export const GET_DANH_SACH_NGUOI_DUNG = 'GET_DANH_SACH_NGUOI_DUNG'
export const DANH_SACH_PHIM_SEARCH = 'DANH_SACH_PHIM_SEARCH'
export const ISSEARCH = 'ISSEARCH'